### ISSUE TITLE
README.md and tag mismatch

### ISSUE THREAD

**Issue by ygqygq2** [willgarcia/workflow-wait-action#2]
```
Error: Unable to resolve action `willgarcia/workflow-wait-action@v0.1.0`, unable to find version `v0.1.0`
```

**Comment by tarxvftech** [comment]
That'd do it.
For anyone looking for the fastest way forward, hitting 'latest version' on the marketplace page shows
` uses: willgarcia/workflow-wait-action@0.1.0`
(note the use of `@0...` instead of `@v0...`
